# Generated by Django 5.1.7 on 2025-03-28 00:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="タイトル"
                    ),
                ),
                ("original_text", models.TextField(verbose_name="元のテキスト")),
                (
                    "summary_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="要約テキスト"
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, null=True, verbose_name="ソースURL"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("url", "URL"),
                            ("pdf", "PDFファイル"),
                            ("text", "直接入力"),
                        ],
                        max_length=50,
                        verbose_name="ソースタイプ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "要約",
                "verbose_name_plural": "要約一覧",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PDFFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="pdf_files/%Y/%m/%d/", verbose_name="PDFファイル"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="ファイル名"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="アップロード日時",
                    ),
                ),
                (
                    "summary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_file",
                        to="text_to_speech_app.summary",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDFファイル",
                "verbose_name_plural": "PDFファイル一覧",
            },
        ),
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(
                        upload_to="audio_files/%Y/%m/%d/", verbose_name="ファイルパス"
                    ),
                ),
                (
                    "is_summary",
                    models.BooleanField(default=False, verbose_name="要約音声"),
                ),
                (
                    "voice_type",
                    models.CharField(
                        choices=[
                            ("nova", "Nova (女性)"),
                            ("alloy", "Alloy (男性風)"),
                            ("echo", "Echo (男性風)"),
                            ("fable", "Fable (男性風)"),
                            ("onyx", "Onyx (男性風)"),
                            ("shimmer", "Shimmer (女性風)"),
                        ],
                        default="nova",
                        max_length=50,
                        verbose_name="音声タイプ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_files",
                        to="text_to_speech_app.summary",
                    ),
                ),
            ],
            options={
                "verbose_name": "音声ファイル",
                "verbose_name_plural": "音声ファイル一覧",
                "ordering": ["-created_at"],
            },
        ),
    ]
